### ISSUE TITLE
Improve a layout of a main text

### ISSUE THREAD

**Issue by akabekobeko** [akabekobeko/redmine-theme-minimalflat2#111]
```css
.wiki p {
  font-feature-settings: "palt" 1;
  text-align: justify;
}
```

* Use an auto kerning
* Use a text justify
