### ISSUE TITLE
When 2+ widgets are placed on the same row on "my page", on small device the view is garbled

### ISSUE THREAD

**Issue by pasqualedante** [akabekobeko/redmine-theme-minimalflat2#115]
On "my page" I have some custom widgets. This widget are placed on the same "row". Whe I access the site from a small device screen, the row with 2 columns isn't switched to 2 rows with 1 column (isn't responsive), and the view on "my page" is garbled.
I attach here 2 screenshot to show issue in action.

large screen
![1](https://user-images.githubusercontent.com/813690/29203442-20d48304-7e71-11e7-82e2-4431dabfd575.png)

small screen
![2](https://user-images.githubusercontent.com/813690/29203451-2e4d8fda-7e71-11e7-9968-fcf5ea64a1cc.png)

**Comment by akabekobeko** [comment]
The default theme `responsive.css` has the following definition.

```css
  .splitcontentleft, #list-left {
    width: 100%;
  }

  .splitcontentright, #list-right {
    width: 100%;
  }
```

In minimalflat2, `#list-left` and `#list-right` are missing. Therefore, it does not become one column. Adding these will be fixed.
