### ISSUE TITLE
A project name overlaps with the switch button while mobile site.

### ISSUE THREAD

**Issue by bibindon** [akabekobeko/redmine-theme-minimalflat2#131]
Thanks for great theme always!
Although sometime I use redmine from mobile phone, a project name is overlaped with the switch button.
I would be grateful if this issue is fixed.

<img width="621" alt="issue" src="https://user-images.githubusercontent.com/39470738/42119623-ff4baa60-7c48-11e8-8d81-e167cdb15b54.png">

**Comment by akabekobeko** [comment]
It is necessary to fix `responsive.css`.

```css
#project-jump .drdn-trigger {
   padding: .3em;
}
```

to

```css
#project-jump .drdn-trigger {
   padding: .3em .3em .3em 1.5em;
}
```

There is no risk, so fix it.
