### ISSUE TITLE
Attachment font size and layout

### ISSUE THREAD

**Issue by iquiw** [akabekobeko/redmine-theme-minimalflat2#135]
In case of attaching files with long name, author names exceed over sidebar area.
![image](https://user-images.githubusercontent.com/238681/47502310-6e33f300-d8a2-11e8-8ce5-e38fd0eac31b.png)

Aside from layout issue, I think it is better to use smaller font size in order not to consume much spaces.

The following is same page with Default theme.
![image](https://user-images.githubusercontent.com/238681/47504047-6ece8880-d8a6-11e8-8266-3467d1e444da.png)

**Comment by iquiw** [comment]
FYI, I'm applying the following CSS by View Customize plugin.
```css
.attachments {
  font-size: .85em;
  line-height: 1;
}
.attachments .size, .attachments .author {
  font-size: .95em;
}
.attachments > table {
  width: 100%;
}
.attachments > table td {
  padding: 1px;
}
```

Here is the result.
![image](https://user-images.githubusercontent.com/238681/47504243-d4bb1000-d8a6-11e8-912c-1e7bcb9b0e74.png)

**Comment by akabekobeko** [comment]
Changing `font-size` may be a relative value, so it may not be described depending on the browser settings. This issue is a problem of `word-break`.

This method can be modified without being affected by `font-size`.

```scss
div.attachments table {
  // Release the float of `.contextual` and adjust the position of edit icon.
  clear: both;
}
div.attachments td {
  // Fix a problem of non line break
  word-break: break-all;
}
```

The attachment will assume a short text of a single line. So I decided that `break-all` is all right.
