### ISSUE TITLE
Style has not been applied to the link of the close the ticket

### ISSUE THREAD

**Issue by akabekobeko** [akabekobeko/redmine-theme-minimalflat2#32]
Compiled CSS is as follows.

```css
a .issue.closed,
a .issue.closed:link,
a .issue.closed:visited {
  color: #95a5a6;
  text-decoration: line-through;
}
```

Expected value

```css
a.issue.closed,
a.issue.closed:link,
a.issue.closed:visited {
  color: #95a5a6;
  text-decoration: line-through;
}
```
